### PR TITLE
Fix E2E dry-run for `Mapping::insert()`

### LINKED ISSUE #1488: `Mapping::insert()` fails in E2E tests
# Summary
When trying to use a message contains `Mapping::insert()` in E2E test, the test errors at dry-run stage for this specific function.

# Reproducer
1. Checkout [gn/mapping-take-tests](https://github.com/paritytech/ink/tree/gn/mapping-take-tests)
2. Navigate to [examples/mappings](https://github.com/paritytech/ink/tree/gn/mapping-take-tests/examples/mappings) folder
3. Run [`substrate-contracts-node V0.21.0`](https://github.com/paritytech/substrate-contracts-node/releases/tag/v0.21.0) - `substrate-contracts-node --dev -linfo,runtime::contracts=debug`
4. Run `RUST_LOG=debug cargo test`
5. You should get the following error message
```
***
2022-11-09T16:02:34Z INFO  ink_e2e] [test: insert_and_get_works] call: [E8, 8D, 16, 46, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]
[2022-11-09T16:02:34Z INFO  ink_e2e] [test: insert_and_get_works] call dry run: Err(Module(ModuleError { index: 7, error: 25, message: None }))
[2022-11-09T16:02:34Z INFO  ink_e2e] [test: insert_and_get_works] call dry run debug message: 
test mappings::e2e_tests::insert_and_get_works ... FAILED

failures:

---- mappings::e2e_tests::insert_and_get_works stdout ----
thread 'mappings::e2e_tests::insert_and_get_works' panicked at 'call failed: CallDryRun', lib.rs:117:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    mappings::e2e_tests::insert_and_get_works

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.23s

error: test failed, to rerun pass '--lib'
***
```

Module error that the message refers to is [`StorageDepositLimitExhausted`](https://github.com/paritytech/substrate/blob/a6da808575fe403ab2bd7f6cd009896cdc6fd71a/frame/contracts/src/lib.rs#L824)

# Edge cases
* Commenting out the code block containing `Mapping::take()` does not cause the problem, so it is definitely to do something with the function.
* Specifying `storage_limit` has no effect
* Executing normal & dry-run call via `cargo-contract` and PolkadotJS app *do not* result in error
* The implementations of dry-run call both in `cargo-contract` and `E2E` crate seem to be the same.

### PR DESCRIPTION
**Pull request by SkymanOne**
This PR fixes #1488 by correctly submitting the origin of the dry-run call during E2E test.

### CODE REVIEW

File: crates/e2e/src/xts.rs [hunk 1]
```diff
@@ -351,13 +351,14 @@ where
     /// Dry runs a call of the contract at `contract` with the given parameters.
     pub async fn call_dry_run(
         &self,
+        account_id: C::AccountId,
```
Comment (HCastano) [inline crates/e2e/src/xts.rs:354]:
```suggestion
        origin: C::AccountId,
```

File: crates/e2e/src/xts.rs [hunk 2]
```diff
@@ -351,13 +351,14 @@ where
...
         contract: C::AccountId,
         value: E::Balance,
         storage_deposit_limit: Option<E::Balance>,
         input_data: Vec<u8>,
     ) -> ContractExecResult<E::Balance> {
         let call_request = RpcCallRequest::<C, E> {
-            origin: contract.clone(),
+            origin: account_id,
```
Comment (HCastano) [inline crates/e2e/src/xts.rs:361]:
```suggestion
            origin,
```

**Review by HCastano — APPROVED** [review]
Thanks!

File: CHANGELOG.md [hunk 3]
```diff
@@ -6,6 +6,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ## [Unreleased]
 - Allows to use `Result<Self, Error>` as a return type in constructors - [#1446](https://github.com/paritytech/ink/pull/1446)
+- Fix E2E dry-run for `Mappping::insert()` - [#1494](https://github.com/paritytech/ink/pull/1494)
```
Comment (HCastano) [inline CHANGELOG.md:9]:
```suggestion
- Fix E2E dry-run for `Mapping::insert()` - [#1494](https://github.com/paritytech/ink/pull/1494)
```
