### PR TITLE
Fix overflow when creating `Layout` in bump allocator tests

### LINKED ISSUE #1323: [ci] Failing fuzz tests on master (18 Jul 2022)
The CI job [1682117](https://gitlab.parity.io/parity/mirrors/ink/-/jobs/1682117) just failed.

The offending commit is [Bump crate versions to 4.0 (#1314)](https://github.com/paritytech/ink/commit/8ba26d89409ca5330c507bffa3999d77fac8d82f).

### PR DESCRIPTION
**Pull request by HCastano**
Looks like I didn't read the `Layout::from_size_align` docs carefully enough and I
should've been checking for `isize` overflows instead of `usize` overflows.

Instead of hand checking this I instead decided to use `from_size_align` directly to
determine if something is valid/invalid.

I've been running the fuzz tests on my machine for a few hours and nothing's failed yet.

Closes #1323.

~~Draft since I need to double check I'm not accidentally changing the intention of some
heap overflow tests.~~

### CODE REVIEW

File: crates/allocator/src/bump.rs [hunk 1]
```diff
@@ -321,28 +314,6 @@ mod fuzz_tests {
         TestResult::passed()
     }
 
-    #[quickcheck]
-    fn should_not_allocate_arbitrary_bytes_if_they_overflow(n: usize) -> TestResult {
```
Comment (cmichi) [inline crates/allocator/src/bump.rs:325]: Could you shortly explain why you think the test is no longer necessary?

Comment (HCastano) [reply crates/allocator/src/bump.rs:325]: I explain in the commit which removed it (https://github.com/paritytech/ink/pull/1336/commits/fe85b7e93afc55c91d1488e58ec61ca52b7e4e1c) 😉

**Review by cmichi — APPROVED** [review]
