### PR TITLE
Conditional compilation 

### LINKED ISSUE #1231: Messages and contstructor cannot be conditionally compiled
Minimal reproducer: https://ink-playground.substrate.io/?id=d666be89f36785e487036bf43d7b175b

It is the same for constructors. I would expect for the message to be just not included in the contract. Instead I get this error:

```
error[E0599]: the function or associated item `call` exists for struct `lol::Lol`, but its trait bounds were not satisfied
--> lib.rs:18:16
|
8 | pub struct Lol {}
| --------------
| |
| function or associated item `call` not found for this
| doesn't satisfy `lol::Lol: std::ops::Fn<_>`
...
18 | pub fn call(&self) {}
| ^^^^ function or associated item cannot be called on `lol::Lol` due to unsatisfied trait bounds
|
= note: the following trait bounds were not satisfied:
`lol::Lol: std::ops::Fn<_>`
which is required by `&lol::Lol: std::ops::Fn<_>`
note: the following trait must be implemented
= help: items from traits can only be used if the trait is implemented and in scope
= note: the following trait defines an item `call`, perhaps you need to implement it:
candidate #1: `std::ops::Fn`
```

### PR DESCRIPTION
**Pull request by SkymanOne**
Closes #1231 

# Summary
This PR introduces a native support for conditional compilation in ink! smart contracts
## High level overview
It is now possible to attribute ink! elements with `#[cfg(...)]` macro attribute. You can use platform specific conditions or custom features specified in `Cargo.toml` file. (See *integration-tests/condtional-compilation* for example).

Important notice: **Attributing event fields is not allowed**.

## Low level overview
IR structures have stayed the same, no significant changes there: just added a helper function to retrieve a list of all `cfg` attributes from the element.

Codegen has undergone some changes. Structures `ContractAmountDispatchables`, `ContractDispatchableMessages` and `ContractDispatchableConstructors` have been removed due to tight dependance on syntax analysis to count the number of elements which do not work with conditional compilation.

Main changes are based around `DispatchableConstructorInfo` and `DispatchableMessageInfo` code generation. Earlier, the logic was based around retrieving dispatchable IDs from the constant array. As mentioned in the #1231, this logic doesn't work when some ink items are omitted at the macro expansion. Therefore, it was decided to explicitly pass dispatchable id in the codegen instead of retrieving it from the array. 

Other changes involve just putting bunch of `cfg` attributes around the codegen to omit associated structures and type definitions at the macro expansion stage.

The feature flag only works with the release of `cargo-contract` which includes: https://github.com/paritytech/cargo-contract/issues/1004

# Checklist

- [x] cargo-contract feature handling - https://github.com/paritytech/cargo-contract/issues/1004
- [x] Inherent messages
- [x] Trait messages
- [x] Constructors
- [x] Events, but not topics
- [x] Disallow event fields to be attributed with `cfg`
- [x] Docs & Cleanup
- [x] Add CI run to build a contract with features

### CODE REVIEW

File: crates/ink/codegen/src/generator/trait_def/call_builder.rs [hunk 1]
```diff
@@ -347,6 +347,7 @@ impl CallBuilder<'_> {
         let mut_tok = message.mutates().then(|| quote! { mut });
         quote_spanned!(span =>
             #[allow(clippy::type_complexity)]
+            #( #attrs )*
```
Comment (xgreenx) [inline crates/ink/codegen/src/generator/trait_def/call_builder.rs:350]: Maybe you want to use `cfg_attrs` here because it is generated part of the trait(not expected by the user)?

File: crates/ink/codegen/src/generator/trait_def/definition.rs [hunk 2]
```diff
@@ -38,6 +38,7 @@ impl<'a> TraitDefinition<'a> {
             format_ident!("{}Output", ident.to_string().to_lower_camel_case());
         quote_spanned!(span =>
             /// Output type of the respective trait message.
+            #(#attrs)*
```
Comment (xgreenx) [inline crates/ink/codegen/src/generator/trait_def/definition.rs:41]: Maybe you want to use `cfg_attrs` here because it is generated part of the trait(not expected by the user)?

File: crates/ink/codegen/src/generator/trait_def/call_forwarder.rs [hunk 3]
```diff
@@ -388,6 +388,7 @@ impl CallForwarder<'_> {
             "encountered error while calling <{forwarder_ident} as {trait_ident}>::{message_ident}",
         );
         quote_spanned!(span =>
+            #( #attrs )*
```
Comment (xgreenx) [inline crates/ink/codegen/src/generator/trait_def/call_forwarder.rs:391]: Maybe you want to use `cfg_attrs` here because it is generated part of the trait(not expected by the user)?

File: crates/ink/codegen/src/generator/trait_def/trait_registry.rs [hunk 4]
```diff
@@ -206,6 +206,7 @@ impl TraitRegistry<'_> {
             }
         };
         quote_spanned!(span=>
+            #( #attrs )*
```
Comment (xgreenx) [inline crates/ink/codegen/src/generator/trait_def/trait_registry.rs:209]: Maybe you want to use `cfg_attrs` here because it is generated part of the trait(not expected by the user)?

File: crates/ink/ir/src/ir/item/event.rs [hunk 5]
```diff
@@ -149,6 +159,22 @@ impl Event {
     pub fn attrs(&self) -> &[syn::Attribute] {
         &self.item.attrs
     }
+
+    /// Returns a list of `cfg` attributes if any.
+    pub fn get_cfg_attrs(&self, span: Span) -> Vec<TokenStream> {
+        self.item
+            .attrs
+            .iter()
+            .filter(|a| a.path.is_ident("cfg"))
```
Comment (xgreenx) [inline crates/ink/ir/src/ir/item/event.rs:168]: It would be nice to put "cfg" into some constant to connect all places together

File: crates/ink/codegen/src/generator/dispatch.rs [hunk 6]
```diff
@@ -182,60 +146,33 @@ impl Dispatch<'_> {
...
+    fn compose_constructors_with_ids(&self) -> Vec<ConstructorDispatchable> {
+        self.contract
             .module()
             .impls()
-            .flat_map(|item_impl| item_impl.iter_constructors())
-            .map(|constructor| {
-                let span = constructor.span();
-                constructor_spans.push(span);
+            .flat_map(|item_impl| {
+                iter::repeat(item_impl.trait_path()).zip(item_impl.iter_constructors())
```
Comment (xgreenx) [inline crates/ink/codegen/src/generator/dispatch.rs:166]: Why do you need `iter::repeat(item_impl.trait_path())` here?

File: crates/ink/codegen/src/generator/as_dependency/call_builder.rs [hunk 7]
```diff
@@ -295,13 +296,15 @@ impl CallBuilder<'_> {
...
         quote_spanned!(span=>
+            #( #cfg_attrs )*
             type #output_ident = <<<
                 Self
                 as ::ink::codegen::TraitCallForwarderFor<{#trait_info_id}>>::Forwarder
                 as ::ink::codegen::TraitCallBuilder>::Builder
                 as #trait_path>::#output_ident;
 
             #[inline]
+            #( #cfg_attrs )*
```
Comment (xgreenx) [inline crates/ink/codegen/src/generator/as_dependency/call_builder.rs:307]: I guess `attrs` already contains `cfg_attrs`, and we can remove it?

File: crates/ink/codegen/src/generator/dispatch.rs [hunk 8]
```diff
@@ -582,41 +538,39 @@ impl Dispatch<'_> {
...
             );
 
+            let constructor_vars = self.generate_constructor_vars(constructors);
+            let constructor_var_idents = Self::generate_constructor_idents(constructors);
+
             quote_spanned!(constructor_span=>
+                #( #cfg_attrs )*
                 Self::#constructor_ident(input) => {
-                    if #any_constructor_accept_payment && #deny_payment {
+                    #( #constructor_vars )*
```
[the remark this answers is not in the document]
Comment (SkymanOne) [reply crates/ink/codegen/src/generator/dispatch.rs:569]: I don't really like the idea of nested functions. They damage the readability of code.

File: crates/ink/ir/src/ir/item_impl/constructor.rs [hunk 9]
```diff
@@ -220,6 +225,22 @@ impl Constructor {
         &self.item.attrs
     }
 
+    /// Returns a list of `cfg` attributes if any.
+    pub fn get_cfg_attrs(&self, span: Span) -> Vec<TokenStream> {
+        self.item
```
Comment (xgreenx) [inline crates/ink/ir/src/ir/item_impl/constructor.rs:230]: Maybe we can move this code into some helper function?(we use the same code in the 4 places)

File: integration-tests/conditional-compilation/lib.rs [hunk 10]
```diff
@@ -0,0 +1,92 @@
...
+}
+
+#[ink::contract]
+pub mod conditional_compilation {
+    use super::Flip;
+
+    /// Feature gated event
+    #[cfg(feature = "foo")]
+    #[ink(event)]
+    pub struct Changes {
```
Comment (xgreenx) [inline integration-tests/conditional-compilation/lib.rs:26]: Could you add one more event with `#[cfg(feature = "bar")]`, please?

File: integration-tests/conditional-compilation/lib.rs [hunk 11]
```diff
@@ -0,0 +1,92 @@
...
+
+    #[ink(storage)]
+    pub struct ConditionalCompilation {
+        value: bool,
+    }
+
+    impl ConditionalCompilation {
+        /// Creates a new flipper smart contract initialized to `false`.
+        #[ink(constructor)]
+        pub fn new() -> Self {
```
Comment (xgreenx) [inline integration-tests/conditional-compilation/lib.rs:41]: Also, it would be nice to have several constructors and messages here compiled conditionally=)

File: integration-tests/conditional-compilation/lib.rs [hunk 12]
```diff
@@ -0,0 +1,92 @@
...
+            Self::env().emit_event(Changes {
+                new_value: value,
+                by: caller,
+            });
+            self.value = value;
+        }
+    }
+
+    #[cfg(test)]
+    mod tests {
```
Comment (xgreenx) [inline integration-tests/conditional-compilation/lib.rs:73]: You also can to add a conditional tests

File: crates/ink/codegen/src/generator/dispatch.rs [hunk 13]
```diff
@@ -401,21 +342,21 @@ impl Dispatch<'_> {
...
         let span = self.contract.module().storage().span();
         let storage_ident = self.contract.module().storage().ident();
-        let any_constructor_accept_payment =
-            self.any_constructor_accepts_payment_expr(constructor_spans);
-        let any_message_accept_payment =
-            self.any_message_accepts_payment_expr(message_spans);
+        let constructor_accept_payment_assignments =
+            self.any_constructor_accepts_payment_vars(constructors);
+        let msg_accepts_payment_assignments =
+            self.any_message_accepts_payment_vars(messages);
```
Comment (xgreenx) [inline crates/ink/codegen/src/generator/dispatch.rs:353]: Previous naming was better=)

File: crates/ink/codegen/src/generator/dispatch.rs [hunk 14]
```diff
@@ -783,65 +725,57 @@ impl Dispatch<'_> {
...
+                    <#storage_ident as ::ink::reflect::DispatchableMessageInfo< #id >>::MUTATES
+                );
 
-            quote_spanned!(message_span=>
-                Self::#message_ident(input) => {
-                    if #any_message_accept_payment && #deny_payment {
-                        ::ink::codegen::deny_payment::<
-                            <#storage_ident as ::ink::env::ContractEnv>::Env>()?;
-                    }
+                let msg_accepts_payment_assignments =
```
Comment (xgreenx) [inline crates/ink/codegen/src/generator/dispatch.rs:750]: `any_message_accept_payment` is better=D

File: .gitlab-ci.yml [hunk 15]
```diff
@@ -400,6 +403,11 @@ examples-contract-build:
     - cargo contract -V
     - for example in integration-tests/*/; do
         if [ "$example" = "integration-tests/lang-err-integration-tests/" ]; then continue; fi;
+        if [ "$example" = "integration-tests/conditional-compilation/" ]; then
+        pushd $example &&
+        cargo +stable contract build --features "foo, bar" &&
```
Comment (xgreenx) [inline .gitlab-ci.yml:408]: Maybe you want to compile it with different combinations of features? Like only with `foo`, only with `bar` and both?

**Review by xgreenx — APPROVED** [review]

File: .gitlab-ci.yml (hunk 15 above)
Comment (SkymanOne) [reply .gitlab-ci.yml:416]: Done

File: crates/ink/ir/src/ir/mod.rs [hunk 16]
```diff
@@ -29,6 +29,23 @@ mod storage_item;
 mod trait_def;
 pub mod utils;
 
+const CFG_IDENT: &str = "cfg";
+
+/// Extracts `cfg` attributes from the given set of attributes
+fn extract_cfg_attributes(attrs: &[syn::Attribute], span: Span) -> Vec<TokenStream> {
```
Comment (ascjones) [inline crates/ink/ir/src/ir/mod.rs:35]: Please move this helper to `utils`

File: CHANGELOG.md [hunk 17]
```diff
@@ -9,6 +9,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 - Basic support for `dyn Trait` to allow cross-contract calls only with trait - [#1673](https://github.com/paritytech/ink/pull/1673)
 - E2E: auto detect contracts to be built - [#1691](https://github.com/paritytech/ink/pull/1691)
 - Add `set_code_hash` to `EnvAccess` - [#1698](https://github.com/paritytech/ink/pull/1698)
+- Support conditional compilation - [#1707](https://github.com/paritytech/ink/pull/1707)
```
Comment (ascjones) [inline CHANGELOG.md:12]: This belongs in `Changed`, as it includes a breaking API change (i.e. the static reflection)

File: crates/ink/tests/ui/contract/pass/constructor-return-result-err.rs [hunk 18]
```diff
@@ -24,18 +24,14 @@ fn main() {
     use contract::Contract;
     use std::any::TypeId;
 
-    const ID: u32 = <Contract as ::ink::reflect::ContractDispatchableConstructors<
-        { <Contract as ::ink::reflect::ContractAmountDispatchables>::CONSTRUCTORS },
-    >>::IDS[0];
```
Comment (ascjones) [inline crates/ink/tests/ui/contract/pass/constructor-return-result-err.rs:29]: We will need to document the breaking change that you can no longer access constructor/message info in this way by the index. But I doubt too many people are depending on that...

**Review by ascjones — APPROVED** [review]
LGTM

File: crates/ink/tests/ui/contract/pass/constructor-return-result-err.rs (hunk 18 above)
Comment (SkymanOne) [reply crates/ink/tests/ui/contract/pass/constructor-return-result-err.rs:29]: Can you please open a separate issue for this?
